name: rents_cars_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  line_icons: ^2.0.3
  supabase_flutter: ^2.5.6
  bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  timeago: ^3.6.1
  location: ^7.0.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  localization: ^2.1.1
  another_flushbar: ^1.12.30
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.7.0
  url_launcher: ^6.3.0
  shimmer: ^3.0.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  shared_preferences: ^2.2.3
  skeletonizer: ^1.3.0
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.6
  flutter_inappwebview: ^6.0.0
  webview_flutter: ^4.8.0
  uuid: ^4.4.2
  dio: ^5.5.0+1
  flutter_countdown_timer: ^4.1.0
  flutter_rating_bar: ^4.0.1
  icons_plus: ^5.0.0
  hugeicons: ^0.0.7
  heroicons_flutter: ^0.4.0
  flutter_svg: ^2.0.10+1
  pdf: ^3.11.1
  path_provider: ^2.1.4
  open_file: ^3.2.1
  flutter_social_button: ^1.1.4+1
  whatsapp: ^3.0.0
  twilio_flutter: ^0.9.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_osm_plugin: ^0.70.4
  flutter_map: ^7.0.2
  printing: ^5.12.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


# For launch icon - flutter pub run flutter_launcher_icons:main
# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/logo.png"
#   adaptive_icon_background: "#ffffff"
#   adaptive_icon_foreground: "assets/images/logo.png"

# # For splash screen -
# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/images/logo.png
#   android_12:
#     image: assets/images/logo.png
#     # icon_background_color: "#FFD1A6"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env.dev
    - .env.prod

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/background.png
  android: true
  ios: false 
  
    
  fonts:
    - family: InterTightPrimary
      fonts:
        - asset: assets/fonts/InterTightBlack.ttf
    - family: InterTightBoldSecondary
      fonts:
        - asset: assets/fonts/InterTightBold.ttf